### ISSUE TITLE
DisableErrSkip() not working as expected

### ISSUE THREAD

**Issue by pmlanger** [nhatthm/otelsql#207]
Hello,
to avoid the `driver: skip fast-path; continue as if unimplemented` error being attached to spans, I added the `DisableErrSkip()` option to the `otelsql.Wrap()` call like this:

`otelsql.Wrap(d, otelsql.WithSystem("mysql"), otelsql.DisableErrSkip())`

However, this hasn't produced the result I expected, as the error was still added to the spans.
I _think_ that this is because `vendor/go.nhat.io/otelsql/driver.go` in `newConnConfig` does not add the `errorToSpanStatus` function to `t.errorToStatus` (`t` being `methodTracerImpl`).
I have patched the lib to add it, and it looks like it's working now (spans are not marked as error any longer, using the option). 
If you agree, I could provide a PR with that change.

Also, do you have any additional insights as to how I could circumvent the error to happen in the first place (using github.com/go-sql-driver/mysql v1.7.1 with MySQL v8)?

Thanks a lot!

**Comment by nhatthm** [comment]
Hey @pmlanger,

Thanks for opening the issue.

> I _think_ that this is because `vendor/go.nhat.io/otelsql/driver.go` in `newConnConfig` does not add the `errorToSpanStatus` function to `t.errorToStatus` (`t` being `methodTracerImpl`). I have patched the lib to add it, and it looks like it's working now (spans are not marked as error any longer, using the option). If you agree, I could provide a PR with that change.

I think you are right 👍 please open a PR as I can't fix this by Monday. Otherwise, I will work on a fix next week.

> Also, do you have any additional insights as to how I could circumvent the error to happen in the first place (using github.com/go-sql-driver/mysql v1.7.1 with MySQL v8)?
> 
> Thanks a lot!

I'm not aware of all the use cases in each driver implementation. If you post some examples of where it happens, I may be able to look into it.

**Comment by pmlanger** [comment]
@nhatthm Oh, you beat me by 5 minutes there :-)
Anyway, maybe it's worth looking at this: https://github.com/nhatthm/otelsql/pull/210 since I have also added a test case.

**Comment by nhatthm** [comment]
@pmlanger :D can you rebase with master then?

**Comment by pmlanger** [comment]
@nhatthm Will do!

**Comment by pmlanger** [comment]
> I'm not aware of all the use cases in each driver implementation. If you post some examples of where it happens, I may be able to look into it.

Just to follow up on this: I have tracked it down to this line in [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql/blob/72e78ee26806a26405ee462c4cf82406f094a143/connection.go#L364). Setting the InterpolateParams config to `true` makes the error disappear.

**Comment by nhatthm** [comment]
Nice!
